{
   "type": "record",
   "name": "inferred_schema",
   "fields": [
      {
         "name": "VALUE1",
         "type": "int",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE2",
         "type": "double",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE3",
         "type": "int",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE4",
         "type": "double",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE5",
         "type": "int",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE6",
         "type": "double",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE7",
         "type": "int",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE8",
         "type": "double",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE9",
         "type": "int",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE10",
         "type": "double",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE11",
         "type": "int",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE12",
         "type": "double",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE13",
         "type": "int",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE14",
         "type": "double",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE15",
         "type": "int",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE16",
         "type": "double",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE17",
         "type": "int",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE18",
         "type": "double",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "VALUE19",
         "type": "int",
         "dataClass": "numerical",
         "role": "predictor",
         "protectedClass": false,
         "driftCandidate": true,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      },
      {
         "name": "DATE_ADDED",
         "type": "string",
         "dataClass": "categorical",
         "role": "prediction_date",
         "protectedClass": false,
         "driftCandidate": false,
         "specialValues": [],
         "scoringOptional": false,
         "pii": false,
         "phi": false
      }
   ]
}